version: '3.8'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - medium_network
  web:
    build: .
    environment:
      - RAILS_SERVE_STATIC_FILES=true
    command: ["./start.sh"]
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - medium_network
volumes:
  pg_data:
networks:
  medium_network: