version: '3.8'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD = ${POSTGRES_PASSWORD}
    volumes:
      - medium_app_data:/var/lib/postgresql/data
    networks:
      - medium_network
  web:
    build: .
    env_file: .env
    command: ["./start.sh"]
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - medium_network
volumes:
  medium_app_data:
networks:
  medium_network: