version: '3.8'
services:
  db:
    image: postgres 
    volumes:
      - medium_app_data:/var/lib/postgresql/data
    networks:
      - medium_network
  web:
    build: .
    env_file: .env
    command: |
      bash -c "rm -f tmp/pids/server.pid && bundle && rails db:create && rails db:migrate && rails db:seed  && rails s -p 3000 -b '0.0.0.0' && rails tailwindcss:watch"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - medium_network
volumes:
  medium_app_data:
networks:
  medium_network: